[package]
name = "nlopt"
version = "0.2.0"
authors = ["Lucas L. Treffenstädt <lucas@treffenstaedt.de>", "Jess Fulwood <jesskfulwood@gmail.com>"]
description = "Wrapper for the nlopt library"
license = "MIT"
repository = "http://github.com/jesskfullwood/rust-nlopt"
readme = "README.md"
keywords = ["nonlinear", "optimization"]

[dev-dependencies]
num-iter = "0.1.35"
